### ISSUE TITLE
Panic on Finish

### ISSUE THREAD

**Issue by akalin-keybase** [keybase/go-framed-msgpack-rpc#15]
```
panic: close of closed channel

goroutine 185 [running]:
github.com/keybase/go-framed-msgpack-rpc.(*call).Finish(0xc820145080, 0x7f0a8d9115a0, 0xc823390e50)
        /home/strib/go/src/github.com/keybase/go-framed-msgpack-rpc/dispatch.go:123 +0x6b
github.com/keybase/go-framed-msgpack-rpc.(*dispatch).callLoop.func1(0xc820145080)
        /home/strib/go/src/github.com/keybase/go-framed-msgpack-rpc/dispatch.go:153 +0x171
created by github.com/keybase/go-framed-msgpack-rpc.(*dispatch).callLoop
        /home/strib/go/src/github.com/keybase/go-framed-msgpack-rpc/dispatch.go:156 +0x5f8
```

**Comment by maxtaco** [comment]
How did you trigger this?

**Comment by akalin-keybase** [comment]
Saw it on https://keybase.atlassian.net/browse/KBFS-463

**Comment by akalin-keybase** [comment]
Solved by https://github.com/keybase/go-framed-msgpack-rpc/pull/14 according to @jzila.

**Comment by jzila** [comment]
Closing since we've closed the JIRA issue.
